apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
data:
  consumer.properties: |
    security.protocol=SSL
    ssl.truststore.location=/var/private/ssl/truststore.jks